---
title: "ENVS-193DS-Final"
author: Max Tu
date: 6/11/25
format: html
toc: true
message: false # use this to make sure messages don't show up
warning: false # use this to make sure warnings don't show up
---

```{r}
library(tidyverse) # reading in packages
library(here)
library(gt)
library(flextable)
library(janitor)
library(readxl)
library(magick)
```

# 1. Research writing

## a. Transparent statistical methods

\[In part 1, they used a correlation test. In part 2, they used an ANOVA test.\]

## b. More information needed

[The first test would be Tukey Honestly Significantly Different (Tukey HSD) test. It compares which sources are actually different when you compare them (like the average nirogen laod (kg year^-1). Another test would be calculating the effect size shows how much the grouping variable explains the response variable (how much the source explains the average nitrogen load (kg year^-1))]

## c. Suggestions for rewriting

[In part 1, we found some correlation between distance from headwater (km) and annual total nitrogen load (kg year-1) (pearson's correlation test, r = correlaton coefficient, p = 0.03, $\alpha$ = significance level). For part 2, we found a difference ($\eta$^2 = effect size) between sources in average nitrogen load (kg year-1) (one-way ANOVA , F(among groups df, within groups df) = test statistic, p = 0.02, $\alpha$ = significance level). On average, urban showed land __ nitrogen load (kg year^-1) (x kg __, % confidence interval: [lower bound, upper bound] kg year^-1) than atmospheric deposition (this can expanded for more variables).]

# 2. Data Visualization

## a. Cleaning and summarizing

```{r}
sst <- read.csv("C:/Users/tuthi/OneDrive/Documents/github/ENVS-193DS_spring-2025_final/data/SST_update2023.csv") # reading in data file
```

```{r}
clean_sst <- sst |> # creating a new dataframe
  clean_names() |> # cleaning up data frame
  filter(year(date) >= 2018 & year(date) <= 2023) |> # setting up the range of years that I want
  mutate(
    date = as.Date(date), # converts to date format in R
    year = year(date), # adds new column for year and extracts year part  from each date column
    month = month(date, label = TRUE, abbr = TRUE) # creates a new column for month and extracts month from date column, while abbreviating month name
  ) |>
  group_by(year, month) |> # pairs up the month and year together 
  summarise(mean_monthly_sst = mean(temp, na.rm = TRUE)) |> # calculate mean surface temperature for each month and year group, rename column
  mutate(year=factor(year)) # converts year column to factor for plotting
```

```{r}
slice_sample(clean_sst, n = 5) # showing 5 random rows from dataset
str(clean_sst)

```

